### ISSUE TITLE
Report FileNotFoundError and fail to start wca-prm agent

### ISSUE THREAD

**Issue by thuang6** [intel/workload-collocation-agent#154]
```
[root@igk-0094 ssg]# python3.6 wca-prm.pex -0 --config /home/ssg/wca_detect_prm_local.yaml -l prm:debug -r prm.detector:ContentionDetector
2019-06-10 07:53:16,255 WARNING  {MainThread} [wca.main] This software is pre-production and should not be deployed to production servers.
2019-06-10 07:53:16,256 INFO     {MainThread} [wca.main] Version wca: 0.4.dev42+g654b405
2019-06-10 07:53:17,028 INFO     {MainThread} [wca.storage] configuring log storage to dump metrics to: '/tmp/metrics.log'
2019-06-10 07:53:17,029 INFO     {MainThread} [wca.storage] configuring log storage to dump metrics to: '/tmp/anomalies.log'
2019-06-10 07:53:17,029 DEBUG    {MainThread} [prm.detector] action_delay: 1, mode config: collect, agg_period: 20
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 352, in execute
  File ".bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 397, in _execute
  File ".bootstrap/pex/pex.py", line 495, in execute_entry
  File ".bootstrap/pex/pex.py", line 510, in execute_pkg_resources
  File "/root/.pex/install/wca-0.4.dev42+g654b405-py3-none-any.whl.874d4d15e7016513b1d0fea1e59abb96d4f2b92b/wca-0.4.dev42+g654b405-py3-none-any.whl/wca/main.py", line 133, in main
    exit_code = runner.run()
  File "/root/.pex/install/wca-0.4.dev42+g654b405-py3-none-any.whl.874d4d15e7016513b1d0fea1e59abb96d4f2b92b/wca-0.4.dev42+g654b405-py3-none-any.whl/wca/runners/measurement.py", line 196, in run
    self._iterate()
  File "/root/.pex/install/wca-0.4.dev42+g654b405-py3-none-any.whl.874d4d15e7016513b1d0fea1e59abb96d4f2b92b/wca-0.4.dev42+g654b405-py3-none-any.whl/wca/runners/measurement.py", line 154, in _iterate
    tasks = self._node.get_tasks()
  File "/root/.pex/install/wca-0.4.dev42+g654b405-py3-none-any.whl.874d4d15e7016513b1d0fea1e59abb96d4f2b92b/wca-0.4.dev42+g654b405-py3-none-any.whl/wca/mesos.py", line 123, in get_tasks
    cgroup_path = find_cgroup(executor_pid)
  File "/root/.pex/install/wca-0.4.dev42+g654b405-py3-none-any.whl.874d4d15e7016513b1d0fea1e59abb96d4f2b92b/wca-0.4.dev42+g654b405-py3-none-any.whl/wca/mesos.py", line 60, in find_cgroup
    with open(f'/proc/{pid}/cgroup') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/106818/cgroup'
```

**Comment by thuang6** [comment]
@ppalucki, it blocks wca/prm integration. would you please help to have a look?

**Comment by ppalucki** [comment]
@thuang6, after the lab restart, we have an issue with Mesos slave (it reports not existing tasks that are in running state). We have implemented the workaround that ignores such tasks (if pid doesn't exist in system)) and @felidadae will reset the state of mesos slave on igk-0094 to fix that.

**Comment by felidadae** [comment]
I fixed the state of mesos slave on igk-094.
