### ISSUE TITLE
Building mutilate example workload Docker image fails

### ISSUE THREAD

**Issue by ipuustin** [intel/workload-collocation-agent#445]
**Describe the bug**

Building Docker image of the `mutilate` example fails.

**To Reproduce**
```
$ cd examples/workloads/mutilate
$ docker build .
Sending build context to Docker daemon  10.75kB
Step 1/7 : FROM centos:7
... ... ... ... ... ...
 ---> b9a6f1ca512b
Step 7/7 : COPY /dist/mutilate_wrapper.pex /usr/bin/mutilate_wrapper.pex
COPY failed: stat /var/lib/docker/tmp/docker-builder028888984/dist/mutilate_wrapper.pex: no such file or directory
```
**Context:**
 - WCA Version as reported by ``./dist/wca.pex --version``
```
$ ./dist/wca.pex --version
Traceback (most recent call last):
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/environment.py", line 253, in _resolve
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/__init__.py", line 818, in resolve pex.vendor._vendored.setuptools.pkg_resources.DistributionNotFound: The 'MarkupSafe>=0.23' distribution was not found and is required by Jinja2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/pex.py", line 391, in execute
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/pex.py", line 89, in _activate
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/environment.py", line 232, in activate
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/environment.py", line 393, in _activate
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/environment.py", line 258, in _resolve
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/orderedset.py", line 39, in update
  File "/home/ipuustin/git/workload-collocation-agent/dist/wca.pex/.bootstrap/pex/environment.py", line 258, in <genexpr>
KeyError: 'Jinja2'

```
Probably this doesn't work if built with Docker...

Using git HEAD `05156a1991e48ac7c2b35eb8b3515305c4dd2dc2`.

**Comment by NabeelShahid7** [comment]
I want to contribute to this issue. Hence I request for the owner's permission to proceed with the same.
